spring:
  datasource:
    # ? ??? ? DB ??? ??? ??? ????? ????? ????
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create #create(?? ??? ??? ??, ??? ?? x), create-drop(create? ???? ??)
    show-sql: true  # ORM?? ??? ??? ??? ???
    properties:
      hibernate:
        format_sql: true  # sql? ????? ???
        use_sql_comments: true #sql? ?? ???
    defer-datasource-initialization: true #data.sql? ???? Hibernate? ?? ??? ???? ??? ??
  sql:
    init:
      mode: always # ALWAYS : ?? ??????? SQL ????? ?????.
